name: build
on: 
  workflow_dispatch: # Put here!!
jobs:
  build:
    strategy:
      matrix:
        java: [ 17-jdk ]
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Publish to Maven local
        run: ./gradlew check build publishToMavenLocal --stacktrace --parallel --warning-mode=fail

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/

      - name: Upload artifacts (Maven Local)
        uses: actions/upload-artifact@v2
        with:
          name: Maven Local
          path: /root/.m2/repository
